# Generated by Django 5.2.4 on 2025-08-29 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adoption', '0001_initial'),
        ('pet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adopt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adoptionhistory',
            name='adopt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to='adoption.adopt'),
        ),
        migrations.AddField(
            model_name='adoptionhistory',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.pet'),
        ),
    ]
